#!/usr/bin/env php
<?php

/**
 * Toybox Command Line
 */

use Toybox\Core\Console\Kernel;

if (! defined("TOYBOX_DIR")) {
    const TOYBOX_DIR = __DIR__;
}

require_once(__DIR__ . "/vendor/autoload.php");

(new Kernel())->run();
